name: Metrics
on:
  schedule: [{ cron: "0 6 * * *" }]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ozng
          filename: github-metrics.svg
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_limit: 8
